### ISSUE TITLE
Jobs API implementation

### ISSUE THREAD

**Issue by slint** [inveniosoftware/invenio-jobs#9]
```[tasklist]
### Tasks
- [ ] https://github.com/inveniosoftware/invenio-jobs/issues/10
- [ ] https://github.com/inveniosoftware/invenio-jobs/issues/11
- [ ] https://github.com/inveniosoftware/invenio-jobs/issues/12
```
